######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 2 22:10:29 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . pics
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MemberInfoArray.h MemberModel.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp MemberInfoArray.cpp MemberModel.cpp
RESOURCES += pics/pixmaps.qrc
