######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 2 15:07:25 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . pics
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MemberModel.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp MemberModel.cpp
RESOURCES += pics/pixmaps.qrc
